from __future__ import annotations

from .common import *

from .image_pool_model import *

def default_source() -> dict[str, Any]:
    return {
        "source_url": "",
        "source_platform": "",
        "title": "",
        "price": "",
        "currency": "",
        "bullets": [],
        "description": "",
        "images": [],
        "image_pool": [],
        "dimensions": {
            "length_cm": "",
            "width_cm": "",
            "height_cm": "",
        },
        "weight_kg": "",
        "material": "",
        "package_contents": [],
        "variants": [],
        "skus": [],
        "collect_status": "",
        "collect_logs": [],
        "collect_diagnostics": default_collect_diagnostics(),
    }


def default_collect_diagnostics() -> dict[str, Any]:
    return {
        "collect_mode": "",
        "source_url": "",
        "normalized_url": "",
        "platform_detected": "",
        "started_at": "",
        "finished_at": "",
        "success": False,
        "partial_success": False,
        "error_code": "",
        "error_message": "",
        "page_title": "",
        "final_url": "",
        "http_status": "",
        "is_login_page": False,
        "is_captcha_page": False,
        "is_security_check_page": False,
        "images_found_count": 0,
        "title_found": False,
        "price_found": False,
        "bullets_found_count": 0,
        "sku_found_count": 0,
        "dimensions_found": False,
        "weight_found": False,
        "html_snapshot_path": "",
        "screenshot_path": "",
        "collected_fields": [],
        "missing_fields": [],
        "next_action": "",
        "checked_at": "",
        "parser_version": "collect-v2",
    }


def default_pricing(platform: str = "") -> dict[str, Any]:
    platform_key = str(platform or "").strip().lower()
    return {
        "platform": platform_key,
        "purchase_cost": "",
        "domestic_freight": "",
        "packaging_cost": "",
        "international_shipping": "",
        "other_cost": "",
        "currency_rate": "",
        "weight_kg": "",
        "length_cm": "",
        "width_cm": "",
        "height_cm": "",
        "commission_rate": "",
        "payment_fee_rate": "",
        "shipping_cost": "",
        "warehousing_cost": "",
        "other_platform_fee": "",
        "advertising_cost": "",
        "target_margin": "",
        "cost_breakdown": {},
        "platform_fee_total": "",
        "suggested_price": "",
        "reverse_price": "",
        "expected_profit": "",
        "profit_margin": "",
        "converted_price": "",
        "gross_profit": "",
        "net_profit": "",
        "is_loss": False,
        "pricing_errors": [],
        "checked_at": "",
    }


def default_draft(platform: str) -> dict[str, Any]:
    return {
        "enabled": True,
        "title": "",
        "description": "",
        "bullets": [],
        "search_terms": [],
        "language": "",
        "country": "",
        "site": "",
        "category_id": "",
        "category_path": "",
        "attributes": {},
        "brand": "",
        "model": "",
        "sku": "",
        "upc": "",
        "gtin": "",
        "barcode": "",
        "price": "",
        "stock": "",
        "images": [],
        "package_dimensions": {
            "length_cm": "",
            "width_cm": "",
            "height_cm": "",
            "weight_kg": "",
        },
        "pricing": default_pricing(platform),
        "validation_errors": [],
        "status": "collected",
        "publish_status": "",
        "publish_logs": [],
    }


def default_product_model() -> dict[str, Any]:
    return {
        "name": "",
        "brand": "",
        "category": "",
        "target_customer": "",
        "source_images": [],
        "source_image_urls": [],
        "source_url": "",
        "source_platform": "",
        "materials": [],
        "dimensions": "",
        "colors": [],
        "selling_points": [],
        "package_includes": [],
        "avoid_claims": [],
        "marketplace_terms": {
            "mercadolibre": {
                "language": "es-MX",
                "product_type": "",
                "primary_keywords": [],
                "attribute_keywords": [],
            },
            "wildberries": {
                "language": "ru-RU",
                "product_type": "",
                "primary_keywords": [],
                "attribute_keywords": [],
            },
        },
        "attributes": {},
        "detail_images": [],
        "detail_image_urls": [],
        "listing_overrides": {},
        "copy_results": {},
        "sku_items": [],
        "selected_sku_indices": [],
        "pricing_defaults": {},
        "publish_preview": {},
        "detected_price_display": "",
        "detected_price": "",
        "detected_currency": "",
        "sku": "",
        "model": "",
        "weight_kg": "",
        "stock": "",
        "upc": "",
        "collect_status": "",
        "collect_logs": [],
        "category_id": "",
        "wb_subject_id": "",
        "ozon_category_id": "",
        "local_platform_categories": {},
        "description": "",
        "source": default_source(),
        "drafts": {platform: default_draft(platform) for platform in PLATFORMS},
    }
