from __future__ import annotations

"""Mercado Libre 发布错误的稳定业务码。"""

MERCADOLIBRE_PACKAGE_CARRIER_LIMIT_EXCEEDED = (
    "MERCADOLIBRE_PACKAGE_CARRIER_LIMIT_EXCEEDED"
)
MERCADOLIBRE_LOCAL_RATE_LIMITED = "MERCADOLIBRE_LOCAL_RATE_LIMITED"
MERCADOLIBRE_MARKET_NOT_OPERABLE = "MERCADOLIBRE_MARKET_NOT_OPERABLE"
MERCADOLIBRE_SHIPPING_MODE_NOT_SUPPORTED = (
    "MERCADOLIBRE_SHIPPING_MODE_NOT_SUPPORTED"
)
MERCADOLIBRE_PARENT_CATEGORY_IMMUTABLE = (
    "MERCADOLIBRE_PARENT_CATEGORY_IMMUTABLE"
)
MERCADOLIBRE_PARENT_PAYLOAD_IDENTITY_MISSING = (
    "MERCADOLIBRE_PARENT_PAYLOAD_IDENTITY_MISSING"
)
MERCADOLIBRE_PARENT_PAYLOAD_IMMUTABLE = (
    "MERCADOLIBRE_PARENT_PAYLOAD_IMMUTABLE"
)

__all__ = [
    "MERCADOLIBRE_LOCAL_RATE_LIMITED",
    "MERCADOLIBRE_MARKET_NOT_OPERABLE",
    "MERCADOLIBRE_PACKAGE_CARRIER_LIMIT_EXCEEDED",
    "MERCADOLIBRE_PARENT_CATEGORY_IMMUTABLE",
    "MERCADOLIBRE_PARENT_PAYLOAD_IDENTITY_MISSING",
    "MERCADOLIBRE_PARENT_PAYLOAD_IMMUTABLE",
    "MERCADOLIBRE_SHIPPING_MODE_NOT_SUPPORTED",
]
